class NotFoundException(Exception):
    pass

class AlreadyExistsException(Exception):
    pass